# Generated by Django 4.0.7 on 2023-01-04 23:25

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('contact_phone', models.TextField(validators=[django.core.validators.MinLengthValidator(11, 'Phone number must have at least 11 digits')])),
                ('contact_email', models.TextField(validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=75)),
                ('area_name', models.CharField(max_length=75)),
                ('area_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'Comment must be greater than 3 characters')])),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='splitter.make')),
            ],
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fee', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('comments', models.TextField(blank=True)),
                ('trailer', models.BooleanField(default=False)),
                ('selfhire', models.BooleanField(default=False)),
                ('tourmanager', models.BooleanField(default=False)),
                ('sleeper', models.BooleanField(default=False)),
                ('foh', models.BooleanField(default=False)),
                ('lampy', models.BooleanField(default=False)),
                ('tech', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.company')),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='splitter.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServicedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.company')),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitter.servicearea')),
            ],
        ),
        migrations.AddField(
            model_name='servicearea',
            name='companies',
            field=models.ManyToManyField(through='splitter.ServicedArea', to='splitter.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='service_areas',
            field=models.ManyToManyField(through='splitter.ServicedArea', to='splitter.servicearea'),
        ),
    ]
